// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CatalogService.CompiledModels
{
    [DbContext(typeof(CatalogDbContext))]
    public partial class CatalogDbContextModel : RuntimeModel
    {
        static CatalogDbContextModel()
        {
            var model = new CatalogDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static CatalogDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
